global:
  imagePullSecrets:
    - name: github-registry-secret

injector:
  replicas: 2
  enabled: true
  leaderElector:
    enabled: true
  image:
    registry: docker.io
    repository: hashicorp/vault-k8s
    tag: "1.7.2"
  agentImage:
    registry: docker.io
    repository: openbao/openbao
    tag: "2.4.3"

server:
  image:
    registry: docker.io
    repository: openbao/openbao
    tag: "2.5.1"
  initContainers:
    - name: final-step
      image: docker.io/library/busybox:1.37.0
  ingress:
    ingressClassName: apisix
    enabled: true
    pathType: Prefix
    tls:
      - secretName: wildcard-tls
