SERVICE_PORT: 8084
CONTAINER_PORT: 8084
DEPLOYMENT_IMAGE_PULL_POLICY: Always
REPOSITORY: "ghcr.io/ednel-rioja/k8s-images/gaia-x-edc-simpl-edc"
TAG: "35a3af2"

ingress:
  host: adapter-infra.{{ .Values.namespaceTag.dataprovider }}.{{ .Values.domainSuffix }}
  tls:
    secretName: adapter-infra-simpl-backend-tls
  annotations:
    acme.cert-manager.io/http01-edit-in-place: "false"
  enabled: false

deployment:
  label: infra-deployment
  